$ANSIBLE_VAULT;1.1;AES256
32623332353866373663633030656630653065653131623731653138623439383861613365303964
6265666564643932313161653036663965386134663865300a666332313538366231313431396337
30623666346238396464343732323330363565346661353638366330356364313134346565313563
3037353834613464320a396337643030323762393732636261633931663734393231393966393231
33333066333962376633363363373862366530633132323032323162666338636237336134626636
31643036633461393330376461633031376433313832393639623632323532343934303730313764
35643335373765373236323836373763613436396239343830363963643037663361613731656632
36346431343066616564363764386363346633353264643334633535363461346334343965623130
63666561616238303862386133633838353535376232326634363930613565363934386439613434
38343865393639313362383537396532656364633665333936626365346266633361623034616530
32303931393139613761333838613161393831376265653836326461353331343131653362393336
35373738393639353237336663663535323734306338636639323532613438636464666137313934
37393131393830613466626365633334656331356130646264356438356664646230383233633461
37363736663035393530636337303336376331316163653335373233616632663738653535333735
36626664366637633130333236613737633863306361386237633430393766386264366665366431
35383433643766393164356230306364663430613730303038653666393232636638626636646333
3730
