---

- name: Create a traefik directory if it does not exist
  ansible.builtin.file:
    path: "{{ base_dir }}"
    state: directory
    mode: '0755'

- name: template docker compose files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ base_dir }}/docker-compose.yml"
    mode: "0644"
  loop:
    - docker-compose.yml
  diff: True

- name: Ensure services are running
  community.docker.docker_compose:
    project_src: "{{ base_dir }}"
    pull: True
  notify: Restart container(s)
